### ISSUE TITLE
Doesn't work Dominoes

### ISSUE THREAD

**Issue by huzefa** [Microsquad/gitpizza#2]
I used this app to order pizza from dominoes but to my surprise the pizza arrived from Pizza Hut!

Please fix.

@NavjotPanesar 
@dbqt 
@rutigs 
@joseph-roque 
@topangad

**Comment by NavjotPanesar** [comment]
You're such a troll Huzefa

**Comment by autoreleasefool** [comment]
Unfortunately, we're currently not looking to support any additional vendors, but we will take this under consideration for future prospects.
